async (page) => {
  const check = (condition, message) => { if (!condition) throw new Error(message); };
  const results = [];
  await page.getByRole('button', {name:'Настройки пакетного перевода: Настройки',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('[id^="uvt-target"]').value === 'uk');
  check(await page.locator('[id^="uvt-source"]').inputValue() === 'en', 'Server source is shown');
  check(await page.locator('[id^="uvt-voice-model"]').inputValue() === 'uk_UA-tetiana-high', 'Server exact voice is shown');
  check(await page.locator('[id^="uvt-local-profile"] option[value="unknown"]').isDisabled(), 'Unverified profiles remain unavailable');
  check(await page.locator('[id^="uvt-local-profile"] option[value="local-quality"]').isDisabled(), 'Missing model is unavailable');
  check(await page.locator('details[open]').count() === 0, 'Advanced sections start collapsed');
  results.push('server defaults, exact voice, unavailable models, progressive disclosure');
  await page.locator('[id^="uvt-source"]').selectOption('de');
  await page.waitForFunction(() => document.querySelector('[id^="uvt-settings-mode"]').value === 'override');
  await page.keyboard.press('Escape');
  check(await page.locator('.uvt-panel').count() === 0, 'Escape closes panel');
  check(await page.evaluate(() => document.activeElement.getAttribute('aria-haspopup') === 'dialog'), 'Escape restores trigger focus');
  await page.getByRole('button', {name:'Подготовить пакетный перевод и синхронную аудиодорожку',exact:true}).click();
  await page.waitForFunction(() => window.uvtFixture.requests.some(r => r.path === '/dub'));
  const override = await page.evaluate(() => window.uvtFixture.requests.find(r => r.path === '/dub').body);
  check(override.settings_mode === 'override' && override.source_lang === 'de' && override.target_lang === 'uk' && override.voice_id === 'uk_UA-tetiana-high', 'Changing source preserves displayed server target and voice');
  check(override.media_candidates.includes('https://cdn.example.test/early/master.m3u8'), 'Early resource observer candidate survives timing buffer');
  check(await page.getByRole('progressbar').isVisible(), 'Job progress is accessible');
  check(await page.locator('video').evaluate(v => v.paused && v.muted), 'Starting translation leaves playback and mute alone');
  await page.getByRole('button', {name:'Отменить подготовку пакетного перевода',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('.uvt-progress').hidden);
  results.push('manual override payload, retained early manifest, progress, unchanged playback, cancel');
  await page.getByRole('button', {name:/Настройки пакетного перевода:/}).click();
  await page.locator('[id^="uvt-settings-mode"]').selectOption('server');
  await page.waitForFunction(() => document.querySelector('[id^="uvt-target"]').value === 'uk');
  await page.keyboard.press('Escape');
  await page.getByRole('button', {name:'Подготовить пакетный перевод и синхронную аудиодорожку',exact:true}).click();
  await page.waitForFunction(() => window.uvtFixture.requests.filter(r => r.path === '/dub').length === 2);
  const server = await page.evaluate(() => window.uvtFixture.requests.filter(r => r.path === '/dub')[1].body);
  check(server.settings_mode === 'server' && !('target_lang' in server) && !('voice_id' in server) && !('profile_id' in server), 'Server mode omits manual fields');
  await page.getByRole('button', {name:'Отменить подготовку пакетного перевода',exact:true}).click();
  await page.waitForFunction(() => document.querySelector('.uvt-progress').hidden);
  results.push('return to server defaults preserves API authority');
  await page.getByRole('button', {name:/Настройки пакетного перевода:/}).click();
  await page.locator('[id^="uvt-local-profile"]').selectOption('local-natural');
  await page.waitForFunction(() => document.querySelector('.uvt-profile-guide').textContent.includes('Тяжёлый'));
  results.push('heavy profile caveat');
  await page.setViewportSize({width:390,height:844});
  await page.waitForFunction(() => {const p=document.querySelector('.uvt-panel'), r=p.getBoundingClientRect();return r.left>=0 && r.right<=innerWidth && getComputedStyle(p).gridTemplateColumns.split(' ').length === 1;});
  const fits = await page.locator('.uvt-panel').evaluate(p => {const r=p.getBoundingClientRect(); return r.left>=0 && r.right<=innerWidth && p.scrollWidth<=p.clientWidth && getComputedStyle(p).gridTemplateColumns.split(' ').length === 1;});
  check(fits, 'Narrow screen panel fits without horizontal scrolling');
  await page.locator('.uvt-panel').evaluate(p => {p.scrollTop=p.scrollHeight;});
  const closeVisible = await page.getByRole('button', {name:'Закрыть настройки перевода',exact:true}).evaluate(b => {const br=b.getBoundingClientRect(), pr=b.closest('.uvt-panel').getBoundingClientRect();return br.top>=pr.top && br.bottom<pr.bottom;});
  check(closeVisible, 'Sticky close stays visible while scrolling');
  results.push('390 px layout and sticky close');
  await page.evaluate(() => {window.uvtFixture.unavailable=true;});
  await page.locator('[id^="uvt-target"]').selectOption('ru');
  await page.waitForFunction(() => document.querySelector('.uvt-panel').textContent.includes('Сервер недоступен.'));
  check(await page.locator('[id^="uvt-local-profile"]').isDisabled(), 'Offline model selector is disabled');
  results.push('offline recovery with unverified selector disabled');
  return {passed:results};
}
